#!/usr/bin/env python3
"""Render the Homebrew formula for a suzu release.

Reads the release tag and its SHA256SUMS, and emits Formula/suzu.rb for
every platform the release actually carries — the macOS tier joins the
formula the day its archives exist. Surprising target combinations fail
loudly rather than installing a wrong binary.

Usage: render_tap_formula.py <tag> <sha256sums-file>
"""

from __future__ import annotations

import sys
from pathlib import Path

HEADER = """\
# Suzu — a tiny bell for your machines (sylin-org/suzu).
# GENERATED by .github/scripts/render_tap_formula.py — do not edit by
# hand; the publish workflow re-renders it per release. Homebrew itself
# needs glibc, so Linux rides the gnu archive (musl hosts install the
# binary directly from the release). The macOS tier appears here when
# its archives ship.
# Users: brew install sylin-org/tap/suzu
class Suzu < Formula
  desc "A tiny bell for your machines — companion displays for software events"
  homepage "https://sylin.org/suzu/"
  version "{version}"
  license "MIT"
"""

ARCH_DEP = "  depends_on arch: :x86_64\n"

ON_LINUX = """\

  on_linux do
{gnu}  end
"""

ON_MACOS = """\

  on_macos do
{arm}{intel}  end
"""

FOOTER = """\

  def install
    bin.install "suzu"
  end

  def caveats
    <<~EOS
      The binary carries its own hardware manifests, firmware payloads,
      and workbench UI. Deploy the service (systemd or OpenRC):
        sudo suzu install
      then open the workbench: http://127.0.0.1:7899
      First steps: suzu scan · suzu prepare · suzu serve
    EOS
  end

  def test
    assert_match version.to_s, shell_output("#{bin}/suzu version")
  end
end
"""

BLOCK = """\
    url "https://github.com/sylin-org/suzu/releases/download/v{version}/{file}"
    sha256 "{sha}"
"""


def render(version: str, shas: dict[str, str]) -> str:
    def block(target: str, indent: str = "") -> str:
        if target not in shas:
            raise SystemExit(f"render_tap_formula: no checksum for {target}")
        file = f"suzu-v{version}-{target}.tar.gz"
        body = BLOCK.format(version=version, file=file, sha=shas[target])
        # BLOCK carries a 4-space base; deepen it by replacement, not
        # addition, so nested blocks stay aligned.
        return "".join(
            (line.replace("    ", indent, 1) if line.startswith("    ") else indent + line) + "\n"
            for line in body.rstrip().splitlines()
        )

    out = [HEADER.format(version=version)]

    # The arch guard applies only while every target is x86_64; the day
    # an ARM build exists, the per-platform CPU branches take over.
    if all(t.startswith("x86_64") for t in shas):
        out.append(ARCH_DEP)

    if any(t.startswith(("x86_64-linux", "aarch64-linux")) for t in shas):
        gnu = ""
        if "x86_64-linux-gnu" in shas:
            gnu += "    if Hardware::CPU.intel?\n" + block("x86_64-linux-gnu", "      ") + "    end\n"
        if "aarch64-linux-gnu" in shas:
            gnu += "    if Hardware::CPU.arm?\n" + block("aarch64-linux-gnu", "      ") + "    end\n"
        out.append(ON_LINUX.format(gnu=gnu))

    if any(t.endswith("apple-darwin") for t in shas):
        arm = ""
        intel = ""
        if "aarch64-apple-darwin" in shas:
            arm = "    if Hardware::CPU.arm?\n" + block("aarch64-apple-darwin", "      ") + "    end\n"
        if "x86_64-apple-darwin" in shas:
            intel = "    if Hardware::CPU.intel?\n" + block("x86_64-apple-darwin", "      ") + "    end\n"
        out.append(ON_MACOS.format(arm=arm, intel=intel))

    out.append(FOOTER)
    return "".join(out)


def main() -> None:
    tag = sys.argv[1] if len(sys.argv) > 1 else ""
    sums = Path(sys.argv[2] if len(sys.argv) > 2 else "SHA256SUMS")
    if not tag.startswith("v") or not sums.is_file():
        raise SystemExit(__doc__)
    shas = {}
    for line in sums.read_text(encoding="utf-8").splitlines():
        sha, _, name = line.partition("  ")
        target = name.strip().removeprefix(f"suzu-{tag}-").removesuffix(".tar.gz").removesuffix(".zip")
        shas[target] = sha
    sys.stdout.write(render(tag.removeprefix("v"), shas))


if __name__ == "__main__":
    main()
